// Note 1: These are manually-defined TypeScript types that mirror the Supabase
// database schema. They serve as a development-time placeholder until the
// Supabase project is connected and types can be auto-generated via:
//   npx supabase gen types typescript --project-id YOUR_PROJECT_ID
// Auto-generated types are preferred in production because they stay in sync
// with the database schema automatically.

// Note 2: This is a union type (also called a "string literal union").
// It restricts the session_type field to exactly these three values.
// TypeScript will throw a compile error if you try to assign "morning"
// (lowercase) or "FullDay" — catching bugs before runtime.
export type SessionType = "Morning" | "Afternoon" | "Overtime"

// Note 3: The User interface represents a row in the "users" table.
// Each field maps to a Supabase column. Fields with "| null" can be
// NULL in the database (e.g., company_name is optional).
export interface User {
  id: string
  email: string
  full_name: string
  program: string
  // Note 4: "string | null" is a TypeScript union type. It means this
  // field can hold either a string value or null. This maps to a nullable
  // column in PostgreSQL. The null case must be handled in the UI
  // (e.g., showing "Not set" when company_name is null).
  company_name: string | null
  target_hours: number
  // Note 5: Timestamps are stored as ISO 8601 strings (e.g., "2026-03-10T12:00:00Z").
  // Supabase returns timestamps as strings in JSON responses, not as Date objects.
  // Use new Date(created_at) or date-fns parse() when you need Date operations.
  created_at: string
  updated_at: string
}

// Note 6: The TimeEntry interface represents a row in the "time_entries" table.
// The user_id field is a foreign key referencing users.id, enforced by both
// PostgreSQL constraints and RLS policies.
export interface TimeEntry {
  id: string
  // Note 7: user_id links this entry to its owner. Row Level Security (RLS)
  // policies use auth.uid() = user_id to ensure users can only access
  // their own entries — even if the client tries to query others' data.
  user_id: string
  date_logged: string
  time_in: string
  time_out: string
  // Note 8: total_minutes is stored as an integer (not fractional hours)
  // to avoid floating-point precision issues. The UI converts this to
  // hours for display: totalMinutes / 60.
  total_minutes: number
  session_type: SessionType
  task_description: string | null
  created_at: string
  updated_at: string
}

// Note 9: The Database interface follows Supabase's generated type pattern.
// It defines Row (full record), Insert (required fields for new records),
// and Update (optional fields for partial updates). This triple structure
// enables type-safe CRUD operations:
//   supabase.from("users").insert(data satisfies Database["public"]["Tables"]["users"]["Insert"])
export interface Database {
  public: {
    Tables: {
      users: {
        Row: User
        // Note 10: Omit<User, "created_at" | "updated_at"> removes fields
        // that are auto-generated by the database (via DEFAULT NOW()).
        // This prevents accidentally passing timestamps during insertion.
        Insert: Omit<User, "created_at" | "updated_at">
        // Note 11: Partial<> makes all fields optional for updates.
        // Omit removes fields that should never be updated (id, timestamps).
        // This allows updates like: { full_name: "New Name" } without
        // requiring all other fields.
        Update: Partial<Omit<User, "id" | "created_at" | "updated_at">>
      }
      time_entries: {
        Row: TimeEntry
        Insert: Omit<TimeEntry, "id" | "created_at" | "updated_at">
        Update: Partial<Omit<TimeEntry, "id" | "user_id" | "created_at" | "updated_at">>
      }
    }
  }
}
